### ISSUE TITLE
Slab Texturing issues

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#1]
`stone_slab` & `smooth_stone_slab` - using same textures

`smooth_red_sandstone_slab` - Red x's on all faces

`smooth_sandstone_slab` - Red x's on sides

[See side by side image](https://cdn.discordapp.com/attachments/545374333883777037/678943129428295710/unknown.png)

Tested with 1.14.4.jar loaded.

**Comment by leMaik** [comment]
What blocks are the two question marks?

**Comment by jackjt8** [comment]
The two question marks are:
`cut_sandstone_slab`
`cut_red_sandstone_slab`
