### ISSUE TITLE
failed to download required libraries. please try again later

### ISSUE THREAD

**Issue by Xedel930** [leMaik/chunky#16]
![image](https://user-images.githubusercontent.com/66183169/83951682-9e2ad280-a809-11ea-8120-707925204d12.png)
How do i fix this? i can't update to 2.10

**Comment by CamelShrimp** [comment]
This same thing happened to me
Also i need to get past this step because it says i don't have a chunky installed yet

**Comment by leMaik** [comment]
Sorry, the nightly build of the release day overwrote my release, changing its md5 sum.

Fixed now, please try updating again. :+1:
