### ISSUE TITLE
Add GPU rendering support

### ISSUE THREAD

**Issue by ghost** [leMaik/chunky#25]
GPU rendering would significantly improve the render times. Could be made possible with OpenCL or Vulkan Compute

**Comment by mruk** [comment]
Isn't it open question in faq? 
https://chunky.llbit.se/faq.html

**Comment by ghost** [comment]
It is, but since this fork adds many more features I decided to create this issue

**Comment by leMaik** [comment]
This fork has since been merged into ChunkyDev/chunky (which I am a maintainer of), so we can track this upstream:

https://github.com/chunky-dev/chunky/issues/289
https://github.com/chunky-dev/chunky/issues/329
