### ISSUE TITLE
re: #1 - Stairs also have some issues

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#3]
![image](https://user-images.githubusercontent.com/3740917/75153039-4b1d8b80-5702-11ea-8d92-cf6f5e41e613.png)

`stone_stairs` seem to have suffered from the renaming and share the same textures as `cobble_stone_stairs`. Not sure if anything else has suffered from this so I'll update as we find them.

**Comment by jackjt8** [comment]
`end_stone_brick_stairs` also uses `stone_brick_stairs` textures.

**Comment by leMaik** [comment]
Fixed the texture, but the it still isn't rotated properly and thus the blocks still look wrong. It affects all stairs (and even more blocks) but it's easy to spot on brick stairs.

![default-30](https://user-images.githubusercontent.com/5544859/75196671-c1e77280-575c-11ea-9a3b-aa9a2b0f656b.png)
