### ISSUE TITLE
Portal blocks lack transparency

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#4]
[upstream]

**In game**
![2020-02-24_18 24 01](https://user-images.githubusercontent.com/3740917/75181226-ad43b400-5735-11ea-9861-97c4937f8818.png)

**1.X**
![1 12 22-62](https://user-images.githubusercontent.com/3740917/75181179-969d5d00-5735-11ea-8775-3dc8ef921e1e.png)
-- block:portal

**2.0**
![lemaik_portal](https://user-images.githubusercontent.com/3740917/75181196-9e5d0180-5735-11ea-9f6c-2bb6b6e23299.png)
-- minecraft:snow (axis=x)

**Comment by leMaik** [comment]
This will be fixed in the next snapshot
