### ISSUE TITLE
Internal glass surface rendering

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#5]
Following discussions on Discord regarding coloured shadows created by Stained Glass two issues with how Stained Glass is being rendered have been noted. This is following off of upstream issue https://github.com/llbit/chunky/issues/450

Behaviour in 1.X is seen to be incorrect as all occluded surfaces are not rendered which is not the behaviour seen in Minecraft; where only adjacent Glass with the same Namespace ID's are.

**Glass Rendering in 1.X** 
![1 4 6_colored_shadows](https://user-images.githubusercontent.com/3740917/75247832-c3e81a80-57ca-11ea-8a50-80351454e1b5.png)

**Glass Rendering in Game**
![2020-02-24_23 44 46](https://user-images.githubusercontent.com/3740917/75247862-d3676380-57ca-11ea-906f-c214474ab07b.png)

**Chunky 2.0** - Glass behaviour was adjusted to be much closer to Minecraft however it is not perfect.
![2 0_beta6_colored_shadows](https://user-images.githubusercontent.com/3740917/75247930-fc87f400-57ca-11ea-8755-d52e41809f94.png)

---

[ ] Internal surface between two adjacent & different glass blocks have an increased brightness compared to Minecraft.
![2 0_beta6_colored_shadows_brightsurface](https://user-images.githubusercontent.com/3740917/75248334-e6c6fe80-57cb-11ea-9cc5-556d5a9afc93.png)

[ ] Internal surface shows incorrect culling of occluded adjacent surfaces of glass with different Namespace IDs
![2 0_beta6_colored_shadows_lines](https://user-images.githubusercontent.com/3740917/75248608-605eec80-57cc-11ea-9d92-d49ed0dc91aa.png)

**Comment by jackjt8** [comment]
Additional images of the two issues:

![2020-02-25_12 51 26](https://user-images.githubusercontent.com/3740917/75249185-a7011680-57cd-11ea-8663-e925dbec03f3.png)

![default-64](https://user-images.githubusercontent.com/3740917/75249193-aa949d80-57cd-11ea-9708-4f22c86d0290.png)

It looks like the occlusion system isn't working correctly for glass viewed through glass. Doesn't appear to be related to one surface in particular.

**Comment by jackjt8** [comment]
![default-64](https://user-images.githubusercontent.com/3740917/75250040-5a1e3f80-57cf-11ea-99fe-ad5767b0a40f.png)

I removed the adjacent rear blocks. As can be seen... The single rear block is being rendered on all sides.

**Comment by leMaik** [comment]
![glass-541](https://user-images.githubusercontent.com/5544859/78611556-8960ab80-7867-11ea-87a3-7eed15b55bab.png)

It now looks like ingame, will be in the next snapshot.
