### ISSUE TITLE
Unknown Item ID popups are annoying

### ISSUE THREAD

**Issue by jackjt8** [leMaik/chunky#6]
An unknown Item ID popup locks the Chunky interface until the Warning is acknowledged.

Loading Chunks on some maps can prompt you with multiple unknown Item ID popups whereby only one of these windows can be "active" at once (on Windows)- Meaning you have to select and acknowledge each one which takes time. If a player has an unknown item ID equipped, like a Elytra, an unknown Item ID popup will always occur on that map.

![image](https://user-images.githubusercontent.com/3740917/75250476-5939dd80-57d0-11ea-8ec8-650a759fafa8.png)

---

Could we compress multiple unknown Item ID warnings into a single window and/or have these warnings not lock up the UI given the nature.

I believe the approach by other software in this regard is better. Here is an example from UE4 whereby you can just ignore the message log window and still interact with the UI. 
![image](https://user-images.githubusercontent.com/3740917/75251001-9b175380-57d1-11ea-87ee-6df22331e0d6.png)

**Comment by leMaik** [comment]
Fixed upstream by https://github.com/chunky-dev/chunky/pull/782
