### ISSUE TITLE
Jack-O-Lanterns Not emitting light.

### ISSUE THREAD

**Issue by JacobKazias** [leMaik/chunky#8]
Jack-O-Lanterns do not emit light in newer versions of chunky. All 3 images were tested with the same settings. 
Tested in 1.4.5-208-gcab971d1(image one), 2.0-beta6(image two), and 1.4.5(image three)

![lemaik chunky](https://user-images.githubusercontent.com/21027848/76487636-a16c1900-63e8-11ea-9190-a0e8761aff99.png)
![2 0 chunky](https://user-images.githubusercontent.com/21027848/76487637-a29d4600-63e8-11ea-882a-166a56792be5.png)
![1 4 5 chunky](https://user-images.githubusercontent.com/21027848/76487639-a335dc80-63e8-11ea-92a1-ce4a1b0470a0.png)

**Comment by leMaik** [comment]
Thanks for reporting this, I'll fix it in the next snapshot.

BTW: It's the same for furnaces, smokers and several other blocks. They all have one thing in common: They're not supposed to emit light on all sides. One day, we might have light maps to do this, but for now the workaround is to just make the entire block emit light.

**Comment by JacobKazias** [comment]
I would honestly prefer they stay emitting light from all sides for my use case (as seen in discord). either way tho thank you!

**Comment by leMaik** [comment]
This will be fixed in the next snapshot:

![lantern-500 denoised](https://user-images.githubusercontent.com/5544859/76683778-feddb100-6606-11ea-848a-26a2683d7e0f.png)
